# # HSV thresholds for white lane
# white_lane:
#   hue:
#     low: 75
#     high: 179
#   saturation:
#     low: 0
#     high: 74
#   value:
#     low: 242
#     high: 255

# # HSV thresholds for yellow lane
# yellow_lane:
#   hue:
#     low: 10
#     high: 64
#   saturation:
#     low: 0
#     high: 255
#   value:
#     low: 100
#     high: 255

## FOR GAZEBO
# HSV thresholds for white lane
white_lane:
  hue:
    low: 0
    high: 179
  saturation:
    low: 0
    high: 74
  value:
    low: 242
    high: 255

# HSV thresholds for yellow lane
yellow_lane:
  hue:
    low: 10
    high: 64
  saturation:
    low: 0
    high: 255
  value:
    low: 100
    high: 255

# ROI settings
roi:
  height_factor: 0.5 # Portion of the image height to use for ROI (from bottom)
