construction:
  # Movement parameters
  linear_speed: 0.08 # Linear speed for forward movement (m/s)
  angular_speed: 1.0 # Angular speed for turning (rad/s)

  # Distance thresholds
  wall_distance_threshold: 0.3 # Distance threshold to consider close to wall (m)
  wall_side_distance_threshold: 3 # Distance threshold to consider close to wall (m)

  # Angle parameters
  front_scan_angle: 4.0 # Angle range to consider as "front" (degrees)
  side_scan_angle: 85.0 # Angle range to consider as "side" (degrees)

  # Turn precision
  turn_precision_threshold: 0.1 # Precision threshold for turn completion (rad)
  turn_linear_speed: 0.08 # Linear speed for turning (m/s)
  desired_radius: 0.2 # Factor to adjust turn radius (m)

  # Ramp mode parameters
  ramp_rotation_angle: 60.0 # Angle to rotate in ramp mode (degrees)
  ramp_front_threshold: 0.375 # Distance threshold for front detection (m)
  ramp_side_threshold: 0.45 # Distance threshold for side detection (m)
  ramp_final_threshold: 0.30 # Distance threshold for final detection (m)
  pivot_angular_speed: 0.5 # Angular speed for pivot turns (rad/s)

  # Robot parameters
  wheel_base: 0.160 # Distance between wheels (m) - TurtleBot3 Burger default
