cross_walking:
  # Camera topic
  camera_topic: "/camera/image"

  # Movement parameters
  forward_speed: 0.08 # Linear speed for forward movement (m/s)

  detection_method: "red_only"
  # detection_method: "combined"

  forward_timeout: 30.0 # Maximum time to move forward looking for crossing (seconds)

  # Detection thresholds
  detection_threshold: 900 # Pixel count threshold to consider crossing detected
  cleared_threshold: 50 # Pixel count threshold to consider crossing cleared

  # ROI parameters
  roi_x: 4 # X position of ROI
  roi_y: 90 # Y position of ROI
  roi_width: 280 # Width of ROI
  roi_height: 75 # Height of ROI

  # Color thresholds for red (two ranges because red wraps in HSV)
  hue_red_low1: 0
  hue_red_high1: 15
  saturation_red_low: 9
  saturation_red_high: 255
  value_red_low: 19
  value_red_high: 255

  hue_red_low2: 170
  hue_red_high2: 180

  # Color thresholds for white
  hue_white_low: 0
  hue_white_high: 180
  saturation_white_low: 0
  saturation_white_high: 30
  value_white_low: 200
  value_white_high: 255
