cross_walking:
  # Camera topic
  camera_topic_front: "/camera/image" # Front camera for crosswalk detection
  camera_topic_lane: "/camera/image_projected_compensated" # Down camera for lane detection

  # Movement parameters
  forward_speed: 0.08 # Linear speed for forward movement (m/s)

  detection_method: "red_only"
  # detection_method: "combined"

  # Detection thresholds
  detection_threshold: 600 # Pixel count threshold to consider crossing detected
  cleared_threshold: 10 # Pixel count threshold to consider crossing cleared

  # Mode selection
  use_lane_following: false # Set to false to use simple moveForward() instead of lane detection

  # ROI parameters
  crosswalk_roi_x: 39 # X position of ROI
  crosswalk_roi_y: 97 # Y position of ROI
  crosswalk_roi_width: 221 # Width of ROI
  crosswalk_roi_height: 108 # Height of ROI

  # Color thresholds for red (two ranges because red wraps in HSV)
  hue_red_low1: 0
  hue_red_high1: 10
  saturation_red_low: 56
  saturation_red_high: 255
  value_red_low: 19
  value_red_high: 255

  hue_red_low2: 170
  hue_red_high2: 180

  # Color thresholds for white
  hue_white_low: 0
  hue_white_high: 180
  saturation_white_low: 0
  saturation_white_high: 30
  value_white_low: 200
  value_white_high: 255
