parking:
  # Camera topics
  camera_topic: "/camera/image_projected_compensated"

  # Movement parameters
  max_linear_speed: 0.1
  max_angular_speed: 1.0
  forward_speed: 0.12
  backward_speed: 0.12
  rotation_speed: 0.6

  parking_forward_distance: 0.45

  sleep_time: 1.0
  scan_threshold_distance: 0.35

  # Color thresholds for lane detection
  # Yellow lane thresholds
  hue_yellow_l: 10
  hue_yellow_h: 64
  saturation_yellow_l: 0
  saturation_yellow_h: 255
  value_yellow_l: 100
  value_yellow_h: 255
