parking:
  # Camera topics
  camera_topic: "/camera/image_projected_compensated"

  # Movement parameters
  max_linear_speed: 0.08
  max_angular_speed: 1.0
  forward_speed: 0.12
  backward_speed: 0.12
  rotation_speed: 0.6
  parking_forward_distance: 0.8
  sleep_time: 3.0
  scan_threshold_distance: 0.5

  border_roi_height_factor: 6 # Divide image height by this to get ROI height
  border_roi_y_factor: 2 # increase it to look higher in the image

  # Dashed line detection parameters
  dashed_roi_height_factor: 6 # Divide image height by this to get ROI height
  dashed_roi_width_factor: 2 # Used to calculate width (width*(factor-2)/factor)
  min_dashed_area: 200 # Minimum white pixel count for dashed line
  max_dashed_area_factor: 0.7 # Maximum dashed area as percentage of border line area
  min_dashed_segments: 2 # Minimum number of segments for dashed line

  # Color thresholds for lane detection
  # Yellow lane thresholds
  hue_yellow_l: 20
  hue_yellow_h: 40
  saturation_yellow_l: 100
  saturation_yellow_h: 255
  value_yellow_l: 100
  value_yellow_h: 255

  # White lane thresholds
  hue_white_l: 0
  hue_white_h: 179
  saturation_white_l: 0
  saturation_white_h: 70
  value_white_l: 165
  value_white_h: 255
