# Speed control parameters
max_linear_speed: 0.2 # Maximum linear speed (m/s)
max_angular_speed: 2 # Maximum angular speed (rad/s)
steering_sensitivity: 5.0 # Steering gain for lane following
non_linear_factor: 1.5 # Non-linear factor for steering response

# Additional parameters
min_linear_speed: 0.05 # Minimum linear speed during sharp turns
speed_reduction_factor: 0.7 # Factor to reduce speed when turning
