traffic_light:
  # Camera topic
  # camera_topic: "/camera/image_projected_compensated"
  camera_topic: "/camera/image"

  # Timing parameters
  green_confirmation_time: 1.0 # Time in seconds to confirm green light

  # Detection thresholds
  red_threshold: 75 # Minimum number of red pixels to detect a red light
  green_threshold: 75 # Minimum number of green pixels to detect a green light

  # ROI parameters
  roi_x: 200 # X position of ROI
  roi_y: 60 # Y position of ROI
  roi_width: 80 # Width of ROI
  roi_height: 120 # Height of ROI

  # Color thresholds for red (two ranges because red wraps in HSV)
  hue_red_low1: 0
  hue_red_high1: 10
  saturation_red_low: 100
  saturation_red_high: 255
  value_red_low: 100
  value_red_high: 255

  hue_red_low2: 170
  hue_red_high2: 180

  # Color thresholds for green
  hue_green_low: 40
  hue_green_high: 80
  saturation_green_low: 100
  saturation_green_high: 255
  value_green_low: 100
  value_green_high: 255
