traffic_light:
  # Camera topic
  # camera_topic: "/camera/image_projected_compensated"
  camera_topic: "/camera/image"

  # Timing parameters
  green_confirmation_time: 0.25 # Time in seconds to confirm green light

  # Detection thresholds
  red_threshold: 100 # Minimum number of red pixels to detect a red light
  green_threshold: 1 # Minimum number of green pixels to detect a green light

  # ROI parameters
  roi_x: 162 # X position of ROI
  roi_y: 140 # Y position of ROI
  roi_width: 15 # Width of ROI
  roi_height: 19 # Height of ROI

  # Color thresholds for red (two ranges because red wraps in HSV)
  hue_red_low1: 0
  hue_red_high1: 11
  saturation_red_low: 1
  saturation_red_high: 255
  value_red_low: 58
  value_red_high: 255

  hue_red_low2: 172
  hue_red_high2: 180

  # Color thresholds for green
  hue_green_low: 89
  hue_green_high: 113
  saturation_green_low: 0
  saturation_green_high: 115
  value_green_low: 203
  value_green_high: 255
