traffic_light:
  # Camera topic
  # camera_topic: "/camera/image_projected_compensated"
  camera_topic: "/camera/image"

  # Timing parameters
  green_confirmation_time: 1.0 # Time in seconds to confirm green light

  # Detection thresholds
  red_threshold: 50 # Minimum number of red pixels to detect a red light
  green_threshold: 50 # Minimum number of green pixels to detect a green light

  # ROI parameters
  roi_x: 190 # X position of ROI
  roi_y: 91 # Y position of ROI
  roi_width: 90 # Width of ROI
  roi_height: 130 # Height of ROI

  # Color thresholds for red (two ranges because red wraps in HSV)
  hue_red_low1: 0
  hue_red_high1: 34
  saturation_red_low: 61
  saturation_red_high: 255
  value_red_low: 60
  value_red_high: 255

  hue_red_low2: 170
  hue_red_high2: 180

  # Color thresholds for green
  hue_green_low: 37
  hue_green_high: 92
  saturation_green_low: 112
  saturation_green_high: 255
  value_green_low: 109
  value_green_high: 255
