tunnel_navigation:
  # Navigation parameters
  navigation_timeout: 300.0 # Maximum time to wait for navigation (seconds)

  # Multiple goal navigation
  goal_total: 1 # Total number of goals to navigate to sequentially

  # Array of goal poses [x, y, yaw]
  goal_poses:
    # - [-1.0, -0.9, -1.57]
    # - [1.5, 2.40, 0.0]
    - [1.41, 1.51, 1.57]
    # - [0.1, 0.1, 1.57]

  # Map saving parameters
  map_base_path: "~/Documents/Autorace2025_Noetic/src/maps/maps4" # Base path for saved maps

  # Default goal (used if goal_poses is not defined, for backward compatibility)
  default_goal:
    x: 1.8
    y: 1.7
    yaw: 0.0 # In radians

  finish_area_width: 0.2 # Width of the square area around goal in meters
  finish_area_timeout: 3.0 # Time in seconds robot must stay in finish area to consider goal reached
